### ISSUE TITLE
Suggested feature: Allow setting user for ssh connection

### ISSUE THREAD

**Issue by Jimbomonkey** [Observatory-Sciences/dls-pmac-control#6]
On a couple of beamlines we have PowerPMACs provided by an external supplier,  These have their own user account configured for when connecting over ssh.    eg ssh user1@172.23.xxx.yyy

At the moment dls-pmac-control.py seems to only connect over ssh using the current fedid.  Please can there be an option to set the user to be used for ssh connections?

**Comment by rjwills28** [comment]
I have added this feature so that you can run the application from the command line with the arguments:
    `dl-pmac-control.py --username=blah --password=xxxx`

Then when connecting to a PowerPMAC, a small pop up will appear with the username and password populated with the values specified. If no arguments are given then the default PowerPMAC username and password will be set but you can still edit these at runtime from the popup.

This feature is available in the released version 3.0.0.

**Comment by Jimbomonkey** [comment]
Thanks for implementing this @rjwills28 
I tried it today but didn't have any luck.  When I clicked connect I got a RHEL7 message stating that the program needed access to my ssh keyring.  Once that was granted it just say "Cannot connect to <IP Address>"
I am able to ssh to this PowerPMAC from the command line

**Comment by rjwills28** [comment]
Hi @JimboMonkey - thanks for trying to test out this feature. Can I just confirm that when you clicked connect that a pop-up did appear allowing you to enter your username and password? Was it after doing so that it failed to connect?

**Comment by Jimbomonkey** [comment]
Hi @rjwills28 - yes that's correct.  The pop-up appeared as expected and was pre-filled with the username and password I had entered from the command line.  Clicking OK on this then opened a RHEL7 prompt for ssh keyring access.  Whether I granted this or not, it always resulted in "Cannot connect to"

**Comment by rjwills28** [comment]
Sorry it's taken me so long to get round to looking at this. 
I tested myself providing an incorrect username+password and in that case I get a pop up saying 'Invalid username or password'. This leads me to think that the issue is the IP address or port as if I also enter an incorrect IP address, I get the 'Cannot connect to ...' error before anything about the username or password. 
The IP + port are definitely correct? And does it prompt for ssh access each time? This is something I do not see.

**Comment by Jimbomonkey** [comment]
I'll double check it again in the upcoming shutdown.
If I'm still having problems maybe we could arrange for you to log in to the beamline remotely to diagnose it with me?

**Comment by rjwills28** [comment]
Yes I am certainly happy to do that so we can get to the bottom of it. I'm a little suspicious of the prompt for ssh keyring access and wonder if this is causing a problem within the Python ssh connection method.

**Comment by rjwills28** [comment]
I _think_ I may have been able to reproduce this issue by setting up my own ssh keyring. It looks like it is possible to get round this using arguments passed into the Python paramiko (i.e. ssh library) connect() method.

I have made these changes to the dls_pmaclib module and released a new version of the dls_pmaccontrol module using the updated library. I have made this the default version on the Diamond system.

If you could test trying to connect again in the shutdown and let me know the outcome that would be great. 
I will leave this issue open until we verify that this has fixed it.

**Comment by Jimbomonkey** [comment]
Thanks @rjwills28 - just tested this and it's working.  Thank you for sorting it!
